[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
baseURL = "https://quocbaohehe.github.io/ThongPortfolio/"
languageCode = "en-us"
title = "Thông Portfolio"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  disableThemeToggle = false
  hideFooter = true

[params.assets]
  customJS = ["js/scroll.js"]
  customCSS = ["css/custom.css"]


[menu]

  [[menu.main]]
  identifier = "experience"
  name = "Experience"
  url = "#experience"
  weight = 1

  [[menu.main]]
  identifier = "education"
  name = "Education"
  url = "#education"
  weight = 2

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "#projects"
  weight = 3