[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
baseURL = "https://quocbaohehe.github.io/ThongPortfolio/"
languageCode = "en-us"
title = "Thông Portfolio"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  disableThemeToggle = false
  hideFooter = true
  showToc = true
  [params.assets]
  extendHead = "partials/extend_head.html"
  extendFooter = "partials/extend_footer.html"
  customJS = ["js/scroll.js", "js/mobile.js"]
  customCSS = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "#home"
  weight = 1

  [[menu.main]]
  identifier = "experience"
  name = "Experience"
  url = "#experience"
  weight = 2

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "#projects"
  weight = 3

  [[menu.main]]
  identifier = "education"
  name = "Education"
  url = "#education"
  weight = 4